# Generated by Django 5.1.1 on 2024-10-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_query_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "query",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="assistant.query",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Response",
        ),
    ]
